config/routes.rb
Rails.application.routes.draw do

  root 'dishes#index'
  resources :dishes

end

app/models/dish.rb
class Dish < ActiveRecord::Base

  has_many :taggings
  has_many :tags, through: :taggings

end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_many :taggings
  has_many :dishes, through: :taggings

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :dish
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  def index
    @dishes = Dish.all
  end

  def create
    @dish = Dish.create(dish_params)
    redirect_to '/dishes'
  end

  def new
    @dish = Dish.new
  end

  def show
    @dish = Dish.find(params[:id])
  end

  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    @dish = Dish.find(params[:id])
    @dish.update(dish_params)
    redirect_to '/dishes'
  end

  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy
    flash[:notice] = "Dish successfully deleted"
    redirect_to '/dishes'
  end

  def dish_params
    params.require(:dish).permit(:name, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/edit.html.erb
<%= form_for @dish do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :price %>
<%= f.text_field :price %>
<%= f.submit %>
<% end %>

app/views/dishes/index.html.erb
<% if @dishes.any? %>
  <table border="1">
    <tr>
      <td>Name</td>
      <td>Price</td>
      <td>Edit</td>
      <td>Delete</td>
    </tr>
    <% @dishes.each do |dish| %>
    <tr>
      <td><%= dish.name %></td>
      <td><%= dish.price %></td>
      <td><%= link_to "Edit #{dish.name}", edit_dish_path(dish) %></td>
      <td><%= link_to "Delete #{dish.name}", dish_path(dish), method: :delete %></td>
    <% end %>
    </tr>
  </table>
  <% else %>
  <h2> No dish added yet </h2>
<% end %>

<form action="/dishes/new" method="get">
  <input type="submit" value="Add a dish">
</form>

app/views/dishes/new.html.erb
<%= form_for @dish do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :price %>
<%= f.text_field :price %>
<%= f.submit %>
<% end %>

app/views/dishes/show.html.erb
<p><%= @dish.name %></p>
<p><%= @dish.price %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TakeawayRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

<%= notice %>
<%= yield %>

</body>
</html>